const QuestionListModel = {
  id: 1,
  name: "First qestion list",
  description: null,
  local: null,
  questions: [
    {
      id: 2,
      type: "SINGLE_SELECT_MULTI_CHOICE",
      name: "Question one",
      description: "Dummy question",
      local: "en",
      timeToPresent: null,
      timeToAnswer: null,
      commentOnTime: null,
      commentOnQuestion: null,
      commentOnAnswering: null,
      body: "What is the capital of Finland?",
      options: ["Helsinki", "Stockholm", "Turku"],
      author: null,
    },
    {
      id: 4,
      type: "SINGLE_SELECT_MULTI_CHOICE",
      name: "Kysymys Yksi",
      description: "Teko Kysymys",
      local: "fi",
      timeToPresent: null,
      timeToAnswer: null,
      commentOnTime: null,
      commentOnQuestion: null,
      commentOnAnswering: null,
      body: "Mitä on Suomen pääkaupunki?",
      options: ["Helsinki", "Tokholma", "Turku"],
      author: null,
    },
    {
      id: 6,
      type: "MULTI_SELECT_MULTI_CHOICE",
      name: "Multi Question",
      description: "About continent question",
      local: "en",
      timeToPresent: null,
      timeToAnswer: null,
      commentOnTime: null,
      commentOnQuestion: null,
      commentOnAnswering: null,
      body: "Some of these are continents?",
      options: ["Africa", "Amerika", "Russia"],
      author: null,
    },
    {
      id: 8,
      type: "MULTI_SELECT_MULTI_CHOICE",
      name: "vaihtoehto Kysymys",
      description: "Teko Kysymys maanosista",
      local: "fi",
      timeToPresent: null,
      timeToAnswer: null,
      commentOnTime: null,
      commentOnQuestion: null,
      commentOnAnswering: null,
      body: "Mitä niitä on maanosaia?",
      options: ["Afrikka", "Amerikka", "Venäjä"],
      author: null,
    },
  ],
};

export default QuestionListModel;
